# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logForm(object):
    def setupUi(self, logForm):
        logForm.setObjectName("logForm")
        logForm.resize(370, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(logForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(logForm)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(logForm)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(logForm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(logForm)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(logForm)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(logForm)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(logForm)
        self.pushButton_2.clicked.connect(logForm.close)
        QtCore.QMetaObject.connectSlotsByName(logForm)

    def retranslateUi(self, logForm):
        _translate = QtCore.QCoreApplication.translate
        logForm.setWindowTitle(_translate("logForm", "Form"))
        self.label.setText(_translate("logForm", "用户名"))
        self.label_2.setText(_translate("logForm", "密码"))
        self.pushButton.setText(_translate("logForm", "登录"))
        self.pushButton_2.setText(_translate("logForm", "退出"))
