# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_schForm(object):
    def setupUi(self, schForm):
        schForm.setObjectName("schForm")
        schForm.resize(972, 813)
        self.verticalLayout = QtWidgets.QVBoxLayout(schForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keybtn = QtWidgets.QRadioButton(schForm)
        self.keybtn.setObjectName("keybtn")
        self.horizontalLayout_2.addWidget(self.keybtn)
        self.codebtn = QtWidgets.QRadioButton(schForm)
        self.codebtn.setObjectName("codebtn")
        self.horizontalLayout_2.addWidget(self.codebtn)
        self.catabtn = QtWidgets.QRadioButton(schForm)
        self.catabtn.setObjectName("catabtn")
        self.horizontalLayout_2.addWidget(self.catabtn)
        self.diffbtn = QtWidgets.QRadioButton(schForm)
        self.diffbtn.setObjectName("diffbtn")
        self.horizontalLayout_2.addWidget(self.diffbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputtxt = QtWidgets.QPlainTextEdit(schForm)
        self.inputtxt.setMaximumSize(QtCore.QSize(16777215, 29))
        self.inputtxt.setObjectName("inputtxt")
        self.horizontalLayout.addWidget(self.inputtxt)
        self.schbtn = QtWidgets.QPushButton(schForm)
        self.schbtn.setMaximumSize(QtCore.QSize(93, 28))
        self.schbtn.setObjectName("schbtn")
        self.horizontalLayout.addWidget(self.schbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.outputlist = QtWidgets.QListWidget(schForm)
        self.outputlist.setMinimumSize(QtCore.QSize(0, 600))
        self.outputlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.outputlist.setObjectName("outputlist")
        self.verticalLayout.addWidget(self.outputlist)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delbtn = QtWidgets.QPushButton(schForm)
        self.delbtn.setMaximumSize(QtCore.QSize(16777215, 28))
        self.delbtn.setObjectName("delbtn")
        self.horizontalLayout_4.addWidget(self.delbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(schForm)
        QtCore.QMetaObject.connectSlotsByName(schForm)

    def retranslateUi(self, schForm):
        _translate = QtCore.QCoreApplication.translate
        schForm.setWindowTitle(_translate("schForm", "Form"))
        self.keybtn.setText(_translate("schForm", "按关键词"))
        self.codebtn.setText(_translate("schForm", "按题号"))
        self.catabtn.setText(_translate("schForm", "按类型"))
        self.diffbtn.setText(_translate("schForm", "按难度"))
        self.schbtn.setText(_translate("schForm", "查询"))
        self.delbtn.setText(_translate("schForm", "删除"))
